### PR TITLE
Update to GHC 9.8.1 and aeson 2.2

### PR DESCRIPTION
**Pull request by jasagredo**

### CODE REVIEW

**Comment by 414owen** [comment]
@tibbe Some of these upgrade PRs in ekg/ekg-json could really use a pair of eyes.  
These packages are all marked as broken in nixpkgs because of dep bounds conflicts.  
It's difficult to use ekg on larger codebases, because other packages will inevitable depend on the newer aeson API...

**Comment by jasagredo** [comment]
I don't want to sound rude and of course I don't know the real reasons, but I think @tibbe no longer will mantain this package. There are several PRs (#12, #17, #18 and this one) that speak about updating the package to newer versions, with no responses. And the latest activity was 4 years ago. 

Perhaps someone should take ownership of it. There exists https://github.com/haskell-github-trust @haskell-github-trust but I don't know if they are willing of taking care of this package.

**Comment by tibbe** [comment]
I haven't been involved in Haskell for about a decade so if someone feels like taking over as the maintainer for the package go right ahead.

**Comment by 414owen** [comment]
@tibbe this sounds like the sensible way forward. Would you mind following the instructions on the haskell-github-trust readme? I'm sure it's easier than if an outsider initiates proceedings.

> Transfer GitHub ownership of the package repository to this organization, https://github.com/haskell-github-trust
> Add https://hackage.haskell.org/user/haskell_github_trust as a Hackage maintainer for the package.

Thanks for building and maintaining these libraries :)

**Comment by tibbe** [comment]
@414owen I don't have permission to transfer the repo to [haskell-github-trust](https://github.com/haskell-github-trust).

**Comment by L0neGamer** [comment]
@tibbe if you wish I'm happy to try to handle this; if you wish, transfer ownership/give me perms, and then I can look into transferring so you don't have to worry about it. 

My profile shows that I'm a maintainer on discord-haskell if that helps you to trust me. 

Happy to help with hackage maintainership too.

**Comment by tibbe** [comment]
> @tibbe if you wish I'm happy to try to handle this; if you wish, transfer ownership/give me perms, and then I can look into transferring so you don't have to worry about it.
> 
> My profile shows that I'm a maintainer on discord-haskell if that helps you to trust me.
> 
> Happy to help with hackage maintainership too.

Transferred.

**Comment by L0neGamer** [comment]
Thank you! If you can give me ownership/maintainership of the hackage package as well that would be appreciated; my user name there is BenjaminMcRae

**Comment by tibbe** [comment]
> Thank you! If you can give me ownership/maintainership of the hackage package as well that would be appreciated; my user name there is BenjaminMcRae

Done.

**Comment by L0neGamer** [comment]
I'm looking into getting ekg-json onto stackage, but that requires make sure deps like ekg-core are up to date as well.

would you be interested in doing what you did above to the below repos as well?
 - ekg
 - ekg-core
 - ekg-statsd

**Comment by L0neGamer** [comment]
Currently ekg-core is in stackage so it's not time sensitive, but if you're not interested in maintaining those packages either I can take the baton.

**Comment by tibbe** [comment]
> BenjaminMcRae

Done

**Comment by L0neGamer** [comment]
Thanks once more!

**Pull request closed without merging**
