### PR TITLE
Support GHC 8.10

### PR DESCRIPTION
**Pull request by jberryman**
This is blocked, I guess, on:  https://github.com/tibbe/ekg-core/pull/38

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@tibbe How do you feel about moving all four `ekg-*` packages into a monorepo with a top-level `cabal.project` (preserving history, of course). This'd simplify CI and people would only need to create one PR for changes like this one that touch multiple packages.

**Comment by jberryman** [comment]
(Just a little ping on this, cheers!)

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
I made a Hackage revision allowing `ekg-json-0.1.0.6` to be built with GHC 8.10.

**Pull request merged**
